### ISSUE TITLE
How can i use my stores as classes

### ISSUE THREAD

**Issue by dmscn** [jeffijoe/koa-es7-boilerplate#27]
### I'm applying TypeScript to my code and using this boilerplate as reference. When i run the app i get this error message: 
```
    →  TSError: ⨯ Unable to compile TypeScript:
    →  src/services/user-service.ts(2,10): error TS2305: Module '"../stores/user-store"' has no exported member 'UserStore'.
    →  
    →      at createTSError (/home/damasceno/dev/forum-api/node_modules/ts-node/src/index.ts:230:12)
    →      at getOutput (/home/damasceno/dev/forum-api/node_modules/ts-node/src/index.ts:336:40)
    →      at Object.compile (/home/damasceno/dev/forum-api/node_modules/ts-node/src/index.ts:369:11)
    →      at Module.m._compile (/home/damasceno/dev/forum-api/node_modules/ts-node/src/index.ts:415:43)
    →      at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    →      at Object.require.extensions.(anonymous function) [as .ts] (/home/damasceno/dev/forum-api/node_modules/ts-node/src/index.ts:418:12)
    →      at Module.load (internal/modules/cjs/loader.js:599:32)
    →      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    →      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    →      at Module.require (internal/modules/cjs/loader.js:637:17)
    →      at require (internal/modules/cjs/helpers.js:22:18)
    →      at Object._loadModulesDeps.require (/home/damasceno/dev/forum-api/node_modules/awilix/src/container.ts:553:18)
    →      at modules.map.m (/home/damasceno/dev/forum-api/node_modules/awilix/src/load-modules.ts:100:33)
    →      at Array.map (<anonymous>)
    →      at Object.loadModules (/home/damasceno/dev/forum-api/node_modules/awilix/src/load-modules.ts:92:26)
    →      at Object.loadModules (/home/damasceno/dev/forum-api/node_modules/awilix/src/container.ts:558:5)
```

This is my `user-store.ts`:
```js
import UserSchema, { User } from '../models/user-model';

export default class UserStore {
  logger: any;

  constructor(logger: any) {
    this.logger = logger;
  }

  async find() {
    this.logger.debug('Getting all users');
    return await UserSchema.find();
  }

  async findOneById(id: String) {
    this.logger.debug(`Getting user with id ${id}`);
    return await UserSchema.findById(id);
  }

  async create(user: User) {
    this.logger.debug(`Creating user with id ${user.id}`);
    return await new UserSchema(user).save();
  }

  async update(id: String, user: User) {
    this.logger.debug(`Updating user with id ${id}`);
    return await UserSchema.findByIdAndUpdate(id, user, { new: true });
  }

  async remove(id: String) {
    this.logger.debug(`Removing user with id ${id}`);
    return UserSchema.findByIdAndRemove(id);
  }
}
```

And this is my `container.ts`

```js
import { Lifetime, InjectionMode, createContainer, asValue, AwilixContainer } from 'awilix';
import { logger } from './logger';

const modulesToLoad: any = [
  ['services/*.ts', Lifetime.SCOPED],
  ['stores/*.ts', Lifetime.SINGLETON]
];

/**
 * @returns {AwilixContainer} The container
 */
export function configureContainer(): AwilixContainer {
  const options: any = {
    injectionMode: InjectionMode.CLASSIC
  };
  return createContainer(options)
    .loadModules(modulesToLoad, {
      cwd: `${__dirname}/..`,
      formatName: 'camelCase'
    })
    .register({
      logger: asValue(logger)
    });
}

```
You can see the complete code here [forum-api](https://github.com/dmscn/forum-api/pull/24)

**Comment by dmscn** [comment]
Damn.... I was importing `UserStore` wrong all this time. Sorry! :sweat:

**Comment by jeffijoe** [comment]
How is this an issue with this project? 😅

The error makes sense though, you are probably importing the user store as a named export and not a default export.

**Comment by dmscn** [comment]
I'm the master submiting dumb issues then finding a ridiculous mistake hahahaha :satisfied:
I tought that it could be a wrong setup to implicit the injection of the services and the stores as classes but it was just a wrong import statement :man_facepalming:

**Comment by jeffijoe** [comment]
No worries! 😄
